Session4
akosighie/ASPNetCoreMasters pull request #3
Opened 2021-06-19 11:11 UTC by akosighie

PR for session4

2021-06-20 04:15 UTC, kevinatgithub commented
Can you please include me as reviewer, thanks

2021-06-26 10:15 UTC, jegtugado requested changes
clean attribute routing

2021-06-26 10:15 UTC, jegtugado commented on DotNetCoreMasters/DotNetCoreMasters/Controllers/ItemsController.cs
> +        [HttpGet("/items/{itemId}")]
because of [Route("[controller]")] on the controller level, there is no need for "/items/". Please clean up the routes.

2021-06-26 10:15 UTC, jegtugado commented on DotNetCoreMasters/DotNetCoreMasters/Controllers/ItemsController.cs
> +        [HttpGet("/items/filterBy")]
this too

2021-06-26 10:15 UTC, jegtugado commented on DotNetCoreMasters/DotNetCoreMasters/Controllers/ItemsController.cs
> +        [HttpPut("/items/{itemId}")]
this too

2021-06-26 10:15 UTC, jegtugado commented on DotNetCoreMasters/DotNetCoreMasters/Controllers/ItemsController.cs
> +        [HttpDelete("/items/{itemId}")]
and this as well

2021-06-28 10:05 UTC, jegtugado requested changes

2021-06-28 10:05 UTC, jegtugado commented on DotNetCoreMasters/DotNetCoreMasters/Controllers/ItemsController.cs
> +        [HttpGet]
need to retain route parameter itemId

2021-06-28 10:05 UTC, jegtugado commented on DotNetCoreMasters/DotNetCoreMasters/Controllers/ItemsController.cs
>          public IActionResult Put(int itemId, [FromBody] ItemCreateBindingModel itemCreateModel)
need to retain route parameter itemId

2021-06-28 10:05 UTC, jegtugado commented on DotNetCoreMasters/DotNetCoreMasters/Controllers/ItemsController.cs
> +        [HttpDelete]
need to retain route parameter itemId

2021-07-05 05:04 UTC, jegtugado requested changes
full of wrong routing in items controller. please refer to the homework.

2021-07-05 05:04 UTC, jegtugado commented on DotNetCoreMasters/DotNetCoreMasters/Controllers/ItemsController.cs
> +        [HttpGet]
wrong routing

2021-07-08 07:59 UTC, jegtugado approved these changes

2021-07-08 08:00 UTC, merged